export const Items = [
	{
		id: 1,
		name: 'Игровая приставка Playstation 5',
		image: '/images/playstation5.png',
		price: 350,
		description: '',
	},
	{
		id: 2,
		name: 'беспроводной пылесос Xiaomi Vacuum Cleaner G20',
		image: '/images/vacuum-cleaner.webp',
		price: 350,
		description: '',
	},
	{
		id: 3,
		name: 'Робот-пылесос Xiaomi Robot Vacuum S10+',
		image: '/images/robot.webp',
		price: 350,
		description: '',
	},
	{
		id: 4,
		name: 'Настольная игра HOBBY WORLD Манчкин',
		image: '/images/manch.webp',
		price: 350,
		description: '',
	},
	{
		id: 5,
		name: 'Набор инструмента Gigant 216 предметов',
		image: '/images/Gigant216.webp',
		price: 350,
		description: '',
	},
	{
		id: 6,
		name: 'Ручной отпариватель Xiaomi',
		image: '/images/steamer.webp',
		price: 350,
		description: '',
	},
	{
		id: 7,
		name: 'Шлем виртуальной реальности Oculus Quest 3S',
		image: '/images/oculus_quest.png',
		price: 350,
		description: '',
	},
	{
		id: 8,
		name: 'Пылесос Karcher WD 2 Plus',
		image: '/images/vacuumcleanerkarcher.webp',
		price: 350,
		description: '',
	},
	{
		id: 9,
		name: 'Робот мойщик окон CHOVERY CL-1',
		image: '/images/CHOVERY.webp',
		price: 350,
		description: '',
	},
	{
		id: 10,
		name: 'Портативная колонка JBL Charge 5',
		image: '/images/JBL.webp',
		price: 350,
		description: '',
	},
	{
		id: 11,
		name: 'Комплект из 4-х пластиковых стульев',
		image: '/images/chairs.webp',
		price: 350,
		description: '',
	},
]
